spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://account-service:8080
          predicates:
            - Path=/accounts/**
        - id: team-service
          uri: http://team-service:8080
          predicates:
            - Path=/teams/**